### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by G-Rath** [pillys/copy-dir#18]
Any chance of getting a `index.d.ts` file for this project, so we can use it with TypeScript?

I'm happy to help with this - I'd imagine the typings would look similar to [`cross-spawn`s](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cross-spawn/index.d.ts) in terms of export (the actual function definition would be different of course).

**Comment by G-Rath** [comment]
This is the current definition file I've created, which I think should do the trick:

```
import { PathLike } from 'fs';

type CopyDirFilter = (state: 'file' | 'directory', filePath: string, fileName: string) => boolean;

declare function copydir(src: PathLike, dest: PathLike, callback: (err: NodeJS.ErrnoException | null) => void): void;
declare function copydir(src: PathLike, dest: PathLike, filter: CopyDirFilter, callback: (err: NodeJS.ErrnoException | null) => void): void;

declare namespace copydir {
  function sync(src: PathLike, dest: PathLike, filter?: CopyDirFilter): void;
}

export = copydir;
```

Please have a look over it and let me know if anythings wrong :)

**Comment by pillys** [comment]
welcome to commit a pull request.
